services:
  app:
    image: ghcr.io/linusfri/carpcalc-ghcr:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=gooption
      - MYSQL_ROOT_PASSWORD="${DB_PW}"
    ports:
      - '33006:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
secrets:
   db_password:
     file: ./secrets/db_password.txt